version: "3.6"
services:
  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    container_name: db
    image: "postgres:11-alpine"
    restart: always
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
  ersventaja:
    build: .
    container_name: ersventaja
    depends_on:
      - db
    environment:
      MIX_ENV: dev
    env_file:
      - .env
    ports:
      - "4000:4000"
    volumes:
      - .:/app
  rsventajaweb:
    image: httpd:latest
    container_name: rsventajaweb
    volumes:
      - "./html:/usr/local/apache2/htdocs"
    ports:
      - "4200:80"
  nginx:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    depends_on:
      - rsventajaweb
      - ersventaja
    ports:
      - 80:80
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
volumes:
  pgdata:
